
server:
  port: 8083
  address: 127.0.0.2
  compression:
    enabled: true
  tomcat:
    max-swallow-size: -1
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  servlet:
    context-path: /    #应用的上下文路径，详细参考 云枢帮助中心-开发者手册-解决跨域安全问题

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tedu?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #redis
  redis:
    host: 127.0.0.1     #地址
    database: 1         #
    password: H3yuncom  #密码
    port: 6379          #端口
   
  #spring session
  session:
    store-type: redis   #存储类型
  mvc:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss    

  thymeleaf:
    cache: false
    check-template: false 
  security:
    oauth:
      sso_uri: http://127.0.0.1:8081

  servlet:
    multipart:
      enabled: true                #默认支持文件上传
      max-file-size: 200MB         #上传单个文件大小限制
      max-request-size: 200MB 
      
      
dubbo:
  application:
    name: cloudpivot-web-api-consumer
    qos-enable: false
    parameters:
      protocol: dubbo
  registry:
    protocol: zookeeper
    address: 127.0.0.1  #服务注册地址
    port: 2181          #端口
    timeout: 3000       #超时时间
    check: true
  consumer:
    check: false
    retries: 0          #重试次数
  provider:
    token: h3bpmtoken
    
       
#指定mapper扫描路径文件
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.tedued.demo






